
server:
  port: 8083

fund:
  service:
    url: http://localhost:8082

logging:
  level:
    p6spy: info
    com.junyoung.cicdgradleproject: debug

spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cicd?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  application:
    name: cicdgradle

agit:
  service:
    url: https://agit.com/send
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      circuitbreakers:
        enabled: true
      ratelimiters:
        enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        minimum-number-of-calls: 100
        failure-rate-threshold: 50
        slow-call-duration-threshold: 60000
        slow-call-rate-threshold: 100
        permitted-number-of-calls-in-half-open-state: 10
    instances:
      money:
        base-config: default
        wait-duration-in-open-state: 30000
        record-exceptions:
          - org.springframework.web.client.RestClientException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
        ignore-exceptions:
          - java.lang.Exception
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 500
    instances:
      money:
        base-config: default
        retry-exceptions:
          - org.springframework.web.client.RestClientException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
        ignore-exceptions:
          - java.lang.Exception
